[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True

[mypy-core.*]
disallow_untyped_defs = True
warn_unreachable = True

[mypy-nzwn.*]
disallow_untyped_defs = True

[mypy-tests.*]
ignore_errors = True

[mypy-experiments.*]
ignore_errors = True
